### ISSUE TITLE
Restringir "crear usuario"

### ISSUE THREAD

**Issue by jfsm1997** [2DAW-2Mares/listaFamiliar#1]
Evitar que al crear un usuario en la aplicacion no puedas asignarle una lista por defecto 
(ejemplo-> "ListafamiliarId": 1)

**Comment by albsierra** [comment]
Solucionado en [este commit](https://github.com/2DAW-2Mares/listaFamiliar/commit/428448d67a3ef7e420af8ff70c11d762450d503f)
